<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>StorybrewCommon</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Debug;Release</Configurations>
    <RootNamespace>StorybrewCommon</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="3.3.3" />
    <PackageReference Include="SkiaSharp" Version="4.152.1" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
    <PackageReference Include="Damnae.Tiny" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\brewlib\brewlib.csproj" />
  </ItemGroup>


</Project>
